Repository Skatteetaten/terraform-nomad-redash, pull requests merged in 2021-05, with the labels that each got.

#37 Updated example/redash_one_node
  .github/workflows/on_pr_master.yml
  .gitignore
  CHANGELOG.md
  LICENSE
  Makefile
  README.md
  dev/ansible/01_run_terraform.yml
  example/datastack/README.md
  example/datastack/hive.tf
  example/datastack/main.tf
  example/datastack/minio.tf
  example/datastack/postgres.tf
  example/datastack/presto.tf
  example/datastack/variables.tf
  example/redash_one_node/main.tf
  example/redash_one_node/nomad_acl.tf
  example/redash_one_node/postgres.tf
  example/redash_one_node/providers.tf
  example/redash_one_node/variables.tf
  main.tf
  nomad/README.md
  nomad/email.hcl
  nomad/redash_scheduler.hcl
  nomad/redash_server.hcl
  nomad/redash_worker.hcl
  nomad/redis.hcl
  outputs.tf
  variables.tf
Labels: type/enhancement

#41 Creating data source dynamically
  CHANGELOG.md
  Makefile
  dev/ansible/00_generate_secrets_vault.yml
  dev/ansible/01_run_terraform.yml
  example/README.md
  example/redash_one_node/main.tf
  example/redash_trino_cluster/README.md
  example/redash_trino_cluster/main.tf
  example/redash_trino_cluster/providers.tf
  example/redash_trino_cluster/variables.tf
  example/resources/images/redash_trino_cluster.png
  main.tf
  nomad/redash_scheduler.hcl
  nomad/redash_server.hcl
  nomad/redash_worker.hcl
  outputs.tf
  variables.tf
Labels: type/enhancement

#44 Issue 43 env vars
  CHANGELOG.md
  main.tf
  nomad/redash_server.hcl
  variables.tf
Labels: type/enhancement

#46 Added health check (redash-server) and updated README.md
  CHANGELOG.md
  README.md
  example/README.md
  example/redash_one_node/README.md
  example/redash_one_node/main.tf
  example/redash_trino_cluster/README.md
  example/redash_trino_cluster/main.tf
  example/resources/images/redash_image_draw.drawio
  example/resources/images/redash_one_node.png
  example/resources/images/redash_trino_cluster.png
  main.tf
  nomad/redash_server.hcl
  variables.tf
Labels: type/documentation, type/enhancement

#48 Release 1.0.0
  CHANGELOG.md
Labels: major
